### ISSUE TITLE
No such service: com.apple.internal.dt.remote.debugproxy

### ISSUE THREAD

**Issue by aymene69** [nythepegasus/SideJIT#1]
192.168.0.18 - - [26/Mar/2024 11:11:19] "GET /x-x/ HTTP/1.1" 200 -
[2024-03-26 11:11:21,268] ERROR in app: Exception on /x-x/Folium [GET]
Traceback (most recent call last):
  File "/Users/us/SideJIT/venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/us/SideJIT/venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/us/SideJIT/venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/us/SideJIT/venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/us/SideJIT/main.py", line 120, in enable_jit_for_app
    app.pid = enable_jit(dev.handle, app.bundle)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/us/SideJIT/main.py", line 55, in enable_jit
    debugserver_host, debugserver_port = device.service.address[0], device.get_service_port('com.apple.internal.dt.remote.debugproxy')
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/us/SideJIT/venv/lib/python3.11/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 112, in get_service_port
    raise InvalidServiceError(f'No such service: {name}')
pymobiledevice3.exceptions.InvalidServiceError: No such service: com.apple.internal.dt.remote.debugproxy

**Comment by nythepegasus** [comment]
Hello! Make sure to mount the disk before trying, that'll be fixed when I next update SideJIT for sure. If the issue still persists definitely reopen this issue.

To mount the disk:
```sh
pymobiledevice3 mounter auto-mount --udid UDID
```

**Comment by nythepegasus** [comment]
For future reference just in case anyone gets here somehow, SideJITServer 1.0.0+ should automatically fix this. I haven't done much testing but mounting the disk still takes a bit for the service to recognize it's mounted.
